name: Build ARM64 JDK for macOS

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Clone the repository
        run: git clone https://github.com/HotswapProjects/openjdk-jdk11u-dcevm.git
      
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf libtool build-essential ccache zip unzip \
                                 libasound2-dev libfreetype6-dev libcups2-dev libx11-dev \
                                 libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev \
                                 g++-aarch64-linux-gnu llvm bison flex
      
      - name: Set up osxcross and sysroot
        run: |
          git clone https://github.com/tpoechtrager/osxcross.git
          cd osxcross
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz -P tarballs/
          sudo ./tools/get_dependencies.sh
          sudo SDK_VERSION=11.3 ./build.sh
          sudo cp -r target/SDK/MacOSX11.3.sdk /opt/aarch64-sysroot
      
      - name: Install mig tool
        run: |
          git clone https://git.savannah.gnu.org/git/hurd/mig.git
          cd mig
          autoreconf -i
          ./configure
          make
          sudo make install
      
      - name: Configure and Build JDK
        env:
          PATH: /usr/lib/llvm-10/bin:$PATH:/usr/local/bin:/home/runner/work/osxcross/target/bin
        run: |
          cd openjdk-jdk11u-dcevm
          bash configure --openjdk-target=aarch64-apple-darwin \
                         --with-sysroot=/opt/aarch64-sysroot \
                         --with-toolchain-path=/home/runner/work/osxcross/target/bin
          make images
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-jdk
          path: openjdk-jdk11u-dcevm/build/macosx-aarch64-normal-server-release/images/jdk
