
name: Build ARM64 JDK for macOS

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone the repository
        run: git clone https://github.com/HotswapProjects/openjdk-jdk11u-dcevm.git
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf libtool build-essential ccache zip unzip libasound2-dev libfreetype6-dev libcups2-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev g++-aarch64-linux-gnu llvm
      - name: Set up sysroot
        run: |
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz
          mkdir -p /opt/aarch64-sysroot
          tar -xJf MacOSX11.3.sdk.tar.xz -C /opt/aarch64-sysroot --strip-components=1
      - name: Configure and Build JDK
        run: |
          cd openjdk-jdk11u-dcevm
          bash configure --openjdk-target=aarch64-apple-darwin --with-sysroot=/opt/aarch64-sysroot --with-toolchain-path=/usr/bin/aarch64-linux-gnu --with-dsymutil=/usr/bin/llvm-dsymutil
          make images
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built-jdk
          path: openjdk-jdk11u-dcevm/build/macosx-aarch64-normal-server-release/images/jdk

